{
    "name": "Latihan Addon academic odoo",
    "version": "1.0",
    "depends": ["base", "account", "board"],
    "author": "khariza",
    "category": "Education",
    "website": "http://vitraining.com",
    "description": "Addon akademik latihan odoo",
    "data": [
        "data/menu.xml",
        "data/course.xml",
        "data/session.xml",
        "data/attendee.xml",
        "data/partner.xml",
        # "data/workflow.xml",
        "data/group.xml",
        "data/ir.model.access.csv",
        "wizard/create_attendee.xml",
        "data/report/session.xml",
        "data/dashboard.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
